plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
remote_theme: pages-themes/hacker@v0.2.0
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - INDEX.md
  - useStateLazyInitialization.md
